### ISSUE TITLE
List of high resolution data sources

### ISSUE THREAD

**Issue by brunosan** [Clay-foundation/model#49] opened 2023-11-22 12:07 UTC
For future iterations, we will consider integrating high resolution imagery to the model as additional input. We can start collecting potential sources for this to have a head start when we get to high resolution data integration.

[Sources must be open data, including commercial use and not be Share-alike]

* [NAIP](https://planetarycomputer.microsoft.com/dataset/naip)
* [2018 Ortofotos from Portugal](https://snig.dgterritorio.gov.pt/rndg/srv/por/catalog.search#/metadata/daf5479d-29c8-4e0c-b7b8-0e1791891186)
* Drone imagery from [OpenAerialMap](https://openaerialmap.org/)

PS: The [EU has recently mandated](https://digital-strategy.ec.europa.eu/en/news/commission-defines-high-value-datasets-be-made-available-re-use) member states to release a list of high value datasets under full and open licensing (CC BY and above). Ortofotos or high res imagery is part of this, so we should look around in the EU for data.

**Comment by weiji14** [comment] 2023-12-10 22:00
Looking at https://registry.opendata.aws/tag/aerial-imagery:

| Dataset | Spatial Resolution | Years | License | Requester Pays | STAC |
|--|--|--|--|--|--|
| [AgricultureVision](https://registry.opendata.aws/intelinair_agriculture_vision) [(GitHub)](https://github.com/SHI-Labs/Agriculture-Vision) | 10cm - ? | 2017-2019 | ? | No | No |
|[KyFromAbove on AWS](https://registry.opendata.aws/kyfromabove) | 7.5cm-15cm (3inch-6inch) | 2010-2022 | Public Domain with Attribution | No | No |
|[NAIP on AWS](https://registry.opendata.aws/naip) | 30cm-100cm | 2010-2021 | Public Domain with Attribution | Yes | No |
|[New Jersey Statewide Digital Aerial Imagery Catalog](https://registry.opendata.aws/nj-imagery) | ? | 1930-2017 | Provided as is | No | No |
| [New Zealand Imagery](https://registry.opendata.aws/nz-imagery) [(GitHub)](https://github.com/linz/imagery) | 5cm-? | 2010?-2023 | [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/) | No | Yes |

The AgricultureVision one looks interesting as it was used for a [2021 CVPR Challenge](https://www.agriculture-vision.com/agriculture-vision-2021/prize-challenge-2021), and we could potentially build a downstream task (semantic segmentation) with it. In terms of other aerial imagery datasets, the NZ imagery is possibly the easiest to integrate with since it has a STAC catalog associated with it, though I'm also biased to having experience working with that dataset extensively in the past :slightly_smiling_face:

**Comment by yellowcap** [comment] 2024-01-22 12:36
Closing as duplicate of #128 . Moving all data into spreadsheet.

**Closed by yellowcap** 2024-01-22 12:36 UTC
